### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by stweil** [bwLehrpool/mltk#1]
I suggest to add a `LICENSE` file in the root source directory.

**Comment by srett** [comment]
Finally got around to it... some day a README might follow :)

**Comment by stweil** [comment]
Thanks. Please add a note in the planned README, too. It is important to know whether the license is "GPL 2 only" or "GPL 2 or later" (which I would suggest).

**Comment by srett** [comment]
Have to check if we can easily do that. Some parts were written before my time and only mention v2, no idea if I can just turn this into ".. or later" without consulting the authors, technically.
